### ISSUE TITLE
The sum of individual character widths in a string doesn't always equal the total

### ISSUE THREAD

**Issue by TerryCavanagh** [haxegon/haxegon#212]
![kerningbug](https://user-images.githubusercontent.com/2874150/35162189-73c85e30-fd3a-11e7-9873-84d0486199b0.png)

Very weird textbounds bug that's messing with some GUI code that I'm working on! Need to figure this one out.

**Comment by increpare** [comment]
looks like it's doing some substitution in the second example?
(double-space fixing and ellipses?)

2018-01-19 18:02 GMT+01:00 Terry Cavanagh <notifications@github.com>:

**Comment by TerryCavanagh** [comment]
Weirdly, the second example is the one that's constituted from piecing together all the different characters! Anyhow, I'll figure it out.

**Comment by TerryCavanagh** [comment]
Huh, found a way worse example:

![kerning2](https://user-images.githubusercontent.com/2874150/35163745-b2343590-fd3f-11e7-84ef-2e46ff646dac.png)

**Comment by TerryCavanagh** [comment]
Gonna leave this for now. A quick Main.hx for testing this issue:

```haxe
import haxegon.*;

@:access(haxegon.Input)
class Main {
	function init(){
		Gfx.resizescreen(320, 180);
	  Gfx.clearcolor = Col.NIGHTBLUE;	
		
		Text.setfont("thin", 1);
	}
	
	function update() {
		Text.input(5, 5);
		
		var reportedwidth:Float = Text.width(Input.keybuffer);
		drawwidth(5, 20, reportedwidth);
		
		var individiualcharacters:Float = 0;
		for (i in 0 ... Input.keybuffer.length){
			individiualcharacters += Text.width(Input.keybuffer.substr(i, 1));
		}
		drawwidth(5, 30, reportedwidth, Col.YELLOW);
		
		//Now let's do this character by character
		var caretpos:Float = 0;
		for (i in 0 ... Input.keybuffer.length){
			Text.display(5 + caretpos, 40, Input.keybuffer.substr(i, 1));
			caretpos += Text.width(Input.keybuffer.substr(i, 1));
		}
		
		drawwidth(5, 55, reportedwidth);
		drawwidth(5, 65, caretpos, Col.YELLOW);
  }
	
	function drawwidth(x:Int, y:Int, w:Float, ?c:Int){
		Gfx.fillbox(x, y, w, 1, (c==null)?Col.WHITE:c);
		Gfx.fillbox(x, y-1, 1, 3, (c==null)?Col.WHITE:c);
		Gfx.fillbox(x + w - 1, y - 1, 1, 3, (c == null)?Col.WHITE:c);
		Text.display(x + w + 2, y - 2, "" + w, (c == null)?Col.WHITE:c);
	}
}
```

**Comment by TerryCavanagh** [comment]
Pushing this back too; openfl seems to be working on textfield stuff right now, maybe it'll fix itself

**Comment by TerryCavanagh** [comment]
This one's still happening on openfl 8 / starling 2.3.1 too. Oh well!

**Comment by TerryCavanagh** [comment]
So happy to finally have figured this one out!
