### ISSUE TITLE
web builds still require ogg files?

### ISSUE THREAD

**Issue by increpare** [haxegon/haxegon#221]
all modern browsers support mp3
https://caniuse.com/#feat=mp3

these browsers support ogg
https://caniuse.com/#feat=ogg-vorbis

**Comment by increpare** [comment]
fwiw, switching everything to mp3 (in the project.xml file and in music.hx) works on safari, chrome, and firefox for me.

**Comment by TerryCavanagh** [comment]
Interesting!

Are you using 0.12.0? There's some pretty substantial changes to the music engine in that which should have meant that if there were .mp3s in the music directory, everything should have worked fine...

**Comment by increpare** [comment]
no. that's probably it :)

**Comment by TerryCavanagh** [comment]
Ok! I've done my own testing with .mp3, .ogg and .wav file support on every major browser and platform to figure the current state of OpenFL and Lime re browser music support. It's looking good!

Using this demo project, which is basically identical expect for what assets are in the data/sounds folder: https://terrycavanaghgames.com/musictest/

Browser | mp3 support? | ogg support? | wav support?
---------|-----------------|-----------------|-----------
Firefox (windows) | yes | yes | yes
Chrome (windows) | yes | yes | yes
Edge (windows) | yes | **NO** | yes
Firefox (mac) | yes | yes | yes
Chrome (mac) | yes | yes | yes
Safari (mac) | yes | **NO** | yes
Mobile Firefox | yes | **NO** | yes 
Mobile Chrome | yes | **NO** | yes
Mobile Safari | yes | **NO** | yes

(I haven't done linux tests, but I'd be shocked if they were different.)

So, yeah, it looks like full browser mp3 support is finally here for Haxe! I'm going to follow suit with Haxegon and update the library and documentation to require mp3s or wavs for browsers in 0.12.0.
