### ISSUE TITLE
Gfx and Text rotation is in angles instead of radians

### ISSUE THREAD

**Issue by TerryCavanagh** [haxegon/haxegon#233]
It's a bit annoying, but have made the decision to use radians everywhere already, so, should keep these consistent too.

Structural, so 0.12.0.

**Comment by TerryCavanagh** [comment]
Deciding to stick to degrees everywhere! Closing this.

**Comment by increpare** [comment]
does this mean you've redfined pi to be 180.0? :P

2018-02-24 19:13 GMT+01:00 Terry Cavanagh <notifications@github.com>:

**Comment by increpare** [comment]
(apologies, that's not constructive! good work on making a decision - you gotta draw the line somewhere!)
