### ISSUE TITLE
random suggestion for Save lib, default values

### ISSUE THREAD

**Issue by increpare** [haxegon/haxegon#249]
consider giving Save.loadvalue a 'default value' parameter.  (Unity does this - see https://docs.unity3d.com/ScriptReference/PlayerPrefs.GetFloat.html for an example).

It can be handy to do

```var char1unlocked = Save.loadvalue("char1unlocked",false)```

or

```var musicVolume = Save.loadvalue("MusicVolume", .5);```

for instance

**Comment by TerryCavanagh** [comment]
This is a great idea. Thanks for the pull request!
