### ISSUE TITLE
mp3 loading errors in firefox on load?

### ISSUE THREAD

**Issue by increpare** [haxegon/haxegon#268]
on firefox on osx, but someone reported it on linux as well

https://ded.increpare.com/~locus/schneespiel/

"uncaught exception: Error: [lime.app.Preloader] ERROR: Error loading asset "data/sounds/blip3.mp3""

( https://github.com/increpare/SchneeSpiel )

**Comment by TerryCavanagh** [comment]
This is also happening on windows! Which is great, because it means I can replicate it! Gonna dig into it right now.

**Comment by TerryCavanagh** [comment]
Oh! There's nothing in the `data/sounds` folder on github - where is it getting the sound from?

**Comment by TerryCavanagh** [comment]
Oh, doh! https://github.com/haxegon/haxegon/issues/269

**Comment by TerryCavanagh** [comment]
Ok, figured this out!

https://github.com/increpare/SchneeSpiel/pull/1

The Haxegon take away here is that it's be nice to have a more accurate error message here: lime reports that it can't find the files, but it can - Firefox just didn't like them in this case.

Unfortunately that's an issue with Lime, so fixing that might involve some pull requests there in future. Anyway! Glad this was sorted out!
