### ISSUE TITLE
Update to Starling 2.4.0

### ISSUE THREAD

**Issue by Doppp** [haxegon/haxegon#279]
Getting this error when building to Windows or Neko.

![code_2018-06-29_17-52-49](https://user-images.githubusercontent.com/627410/42086297-47cf7912-7bc5-11e8-8ae1-35636af813aa.png)

Seems like this was fixed in [later versions](http://community.openfl.org/t/openfl-8-0-1-update/10436/3).

**Comment by TerryCavanagh** [comment]
Ohh, thanks! I’ll look at this today!

**Comment by Doppp** [comment]
@TerryCavanagh any update to this?

**Comment by TerryCavanagh** [comment]
Sorry. Haven’t forgotten, just been super busy with Dicey Dungeons. Should get to it shortly after this next update!

**Comment by TerryCavanagh** [comment]
(Although, I’ve been building to Neko on windows without problems! Is it maybe fixed in the github version?)

**Comment by Doppp** [comment]
And OpenFL... I'm using the latest, maybe I should downgrade.

**Comment by Doppp** [comment]
Closing this because I rolled back my "bleeding edge" tech hah. Still good to update to Starling 2.4.0.

**Comment by TerryCavanagh** [comment]
Worth having open, wanna do this soon anyway!

**Comment by Doppp** [comment]
Alright, sounds good. Yes, the latest git version works but the official release doesn't. Best to have a release soon!

**Comment by TerryCavanagh** [comment]
Ok, done!
