### ISSUE TITLE
stuff seem not to compile with latest version of haxe libs 

### ISSUE THREAD

**Issue by increpare** [haxegon/haxegon#283]
i did a haxelib update...

"/usr/local/lib/haxe/lib/haxegon/0,12,1/starling/utils/SystemUtil.hx:26: characters 7-22 : Type not found : lime.app.Config
Der Terminalprozess wurde mit folgendem Exitcode beendet: 1"

**Comment by TerryCavanagh** [comment]
Hey - yeah, I'm sorry about this, I'm aware! I'm hoping to do a compile fix early next week when I get the new Dicey Dungeons update out.

In the meantime, you can get a working version of haxegon by
 - installing the git version of haxegon locally - `haxelib git haxegon` followed by `https://github.com/haxegon/haxegon`
 - setting the version of openfl and lime to older versions, like this: `haxelib set openfl 8.3.0`, and `haxelib set lime 6.4.0`.

Apologies for the inconvenience! Hope to get this fixed soon!

**Comment by increpare** [comment]
(ah I downgraded everything and it works again. phew!)

2018-08-30 17:34 GMT+02:00 Terry Cavanagh <notifications@github.com>:

**Comment by increpare** [comment]
(thanks!)

2018-08-30 17:44 GMT+02:00 Stephen Lavelle <analytic@gmail.com>:

**Comment by TerryCavanagh** [comment]
Ok, this is fixed now! You can get back up to date by typing:

```
openfl upgrade
haxelib install haxegon
```
