### ISSUE TITLE
Camera Class

### ISSUE THREAD

**Issue by Doppp** [haxegon/haxegon#284]
Not sure if this is on the road map but a camera class would be nice  to have!

**Comment by TerryCavanagh** [comment]
Hey!

I think this sorta thing is probably too high level for Haxegon, to be honest - but how would you imagine it working?

**Comment by Doppp** [comment]
Oh well, I guess if you intend to keep Haxegon as a framework then this won't fit into the roadmap. It would eventually evolve into a full engine like HaxeFlixel.

I just saw that Rauri built his own camera class in OVERWHELM using Haxegon and thought that it would be useful to have. I chatted with him about it and would probably implement it his way.

**Comment by TerryCavanagh** [comment]
Yeah - I feel like things like this belong on another layer, above haxegon! Like, Haxegon has functions to drawtiles, but it doesn't have a map drawing class, and I don't think it should? 🤷‍♂️
