### ISSUE TITLE
Type Issue When Compiling for Flash

### ISSUE THREAD

**Issue by Doppp** [haxegon/haxegon#288]
@TerryCavanagh Getting this bug when just simply opening the `blankproject.zip` (after successfully building and running it).

![error](https://user-images.githubusercontent.com/627410/45264985-85945980-b477-11e8-9ab7-645f30927e91.png)

Here is the bug:

![bug](https://user-images.githubusercontent.com/627410/45265044-57fbe000-b478-11e8-87ea-7e3f01a206cf.png)

And the offending [line](https://github.com/haxegon/haxegon/blob/master/haxegon/Text.hx#L217-L218).

**Comment by TerryCavanagh** [comment]
Cool, thank you! I will look into this ASAP!

**Comment by TerryCavanagh** [comment]
Fixed! Thank you!
