### ISSUE TITLE
project.xml or include.xml?

### ISSUE THREAD

**Issue by Doppp** [haxegon/haxegon#291]
Not really necessary but should we have a `project.xml` or `include.xml` file to get all the dependencies in? That way VS Code won't bork if the libraries are not specified in the User/Workspace settings?

**Comment by TerryCavanagh** [comment]
I haven't used vscode yet - how does it work? Is there a reason to change it?

**Comment by Doppp** [comment]
Almost the same as using HaxeDevelop. When you begin a project in HaxeDevelop you have to set up the `Compiler Options` in the `Properties` section. I believe these settings are then saved in the `.hxproj`.

For normal text editors like VS Code and command line compilation people usually use [project.hxml](https://haxe.org/manual/compiler-usage-hxml.html) files. Just another way of doing the same thing. Most Haxe libraries are using this convention now.

**Comment by TerryCavanagh** [comment]
Cool! As long as it doesn’t break haxedevelop that sounds fine!

(I’ve been meaning to replace the project file in the blank project with a
.hxproj file too, on this subject)

**Comment by Doppp** [comment]
Haha yeah, you should update the blank project. It's outdated-ish.

**Comment by Doppp** [comment]
Actually there's no real need for this. Simple solution would be to include setup instructions for people using VS Code, HaxeDevelop etc. We could use the website or the GitHub wiki.
