### ISSUE TITLE
Any plans for a `Gfx.translate(x, y)` function?

### ISSUE THREAD

**Issue by Greyvy** [haxegon/haxegon#306]
First off, been fiddling around with your engine, and quite enjoying it, strikes a nice balance.

 I’ve noticed the scale and rotate functions for graphics but no translate. I’ve found translate quite useful for building cameras, is there a simple way I could do a similar thing in this engine?

If not perhaps is there a plan to implement translate? If you would like me to have a go at it, I don’t have very much experience with haxe but could give it a shot.

**Comment by TerryCavanagh** [comment]
Hey!

I think a translate function is a great idea, and shouldn't be that much work! I'm happy for you to have a go at it if you like, but also, I'll add it to the to do list and am happy to do it myself when I next update haxegon.

**Comment by TerryCavanagh** [comment]
Implemented. Thank you!
