### ISSUE TITLE
default font lacks accented characters (üöä etc., also ß)

### ISSUE THREAD

**Issue by increpare** [haxegon/haxegon#318]
Do you have the source font for the default anywhere that I could try export it again to get üöäß etc...?

**Comment by TerryCavanagh** [comment]
I am actually having a lot of trouble hunting this down D: I don't seem to have it installed on my computer and am having trouble googling it...

**Comment by TerryCavanagh** [comment]
Ah, wait, no, here we go!

https://www.zone38.net/font/#pcpaint

It's pcpaintnormalsmall.ttf from this: https://www.zone38.net/font/pcpaint-fonts.zip

**Comment by increpare** [comment]
ah ok, looks like it's lackin' in those letter wot I want. Ok :) TY for sourcing it!
