### ISSUE TITLE
way to turn off integer-ratio resizing?

### ISSUE THREAD

**Issue by increpare** [haxegon/haxegon#320]
I'm doing a low-res game on a high resolution device so it's not so important that the ratio be exactly integral. Is there a way to turn that off, or do you have any pointers as to where I should be looking to fiddle?

**Comment by TerryCavanagh** [comment]
This is possible! I think it’s in the gfx resize function, can’t check
exactly how right now though!

**Comment by increpare** [comment]
oh right! thanks :)
