### ISSUE TITLE
add versions to dependencies in haxelib.json

### ISSUE THREAD

**Issue by Kvel2D** [haxegon/haxegon#331]
Currently the latest release of haxegon(0.13.0) obtained with `haxelib install haxegon` doesn't work out of the box because it installs the latest openfl version. A fix would be to change dependencies in haxelib to:

```
"dependencies": { 
    "openfl": "8.4.1", 
    "lime": "7.0.0"
}
````

There's another issue that 0.13.0 is not compatible with the latest haxe version, it requires 3.4.7. Maybe add this requirement to the description of the release and add a link to it?
Also will need to include instructions on how to setup old openfl versions. For me I had to first install the latest version to make `haxelib run openfl setup` work, didn't work with the older version of openfl.

I know that 0.13.0 is quite old but future releases will also lose compatibility and should be setup so that people can use them.

**Comment by TerryCavanagh** [comment]
Hey! We're long overdue an update here, sorry. The latest commit does work with the up to date version of OpenFL, though!

I've had exact version numbers in the haxelib file in the past, and it caused problems - downloading old versions of openfl and lime even when haxegon worked fine with the recent versions, which caused a lot of confusion. While admitted we're overdue a cleanup and there's an issue to be fixed here, requiring a set version of openfl and lime feels like fixing one problem by creating another?

**Comment by Kvel2D** [comment]
Got it, I guess you do want to keep using the latest openfl/lime as long as haxegon is compatible with them. And figuring out the exact point where compatibility breaks is tricky. Including versions of openfl/lime in release notes as has been done is the best option then.
