### ISSUE TITLE
Clean up the use of "magic numbers" in pivot points and alignments

### ISSUE THREAD

**Issue by TerryCavanagh** [haxegon/haxegon#79]
Functions like `Text.align()` and `Gfx.rotation()` use weird constants like `Text.CENTER` and `Gfx.LEFT`, which is (a) pretty unclear and weird, (b) doesn't give useful autocompletion and (c) obscures the fact that you can just pass integers to pivot/align around a specific point. Rethink this whole approach.

**Comment by increpare** [comment]
I LIKE THE MAGIC NUMBERS

**Comment by TerryCavanagh** [comment]
Putting this one forward, not sure how to tackle it best right now

**Comment by TerryCavanagh** [comment]
Ok, on reflection, these constants are great. The only change I'm going to make is to change the default for everywhere that uses these to `Gfx.LEFT`, and to set the `Gfx.LEFT` constant to 0.
